version: '3'
services:
  guide_design:
    volumes:
      - ./services/guide_design:/app/service:ro
      - ../pt_guide_design:/app/packages/pt_guide_design:ro
    command: python -m watchdog.watchmedo auto-restart -d /app/service -p "*.py" -- python service.py

  app:
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev 