version: '3.8'
services:
  guide_design:
    volumes:
      - ./services/guide_design:/app/service:ro
      - ../pt_guide_design:/app/packages/pt_guide_design:ro
    command: python -m watchdog.watchmedo auto-restart -d /app/service -p "*.py" -- python service.py

  app:
    env_file:
      - .env    # Add this if not present
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev 