version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - guide_design
    env_file:
      - .env

  guide_design:
    build:
      context: ..
      dockerfile: server/services/guide_design/Dockerfile
    depends_on:
      - redis
    env_file:
      - .env

  db:
    image: postgres:latest
    platform: linux/arm64/v8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: "redis:latest"
    platform: linux/arm64/v8
    ports:
      - "6379:6379"

volumes:
  postgres_data:
